# Generated by Django 5.1.4 on 2026-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0087_remove_productquality_custom_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
