name: Deploy to Amazon Linux EC2

on:
  push:
    branches:
      - main

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh \
          -o ServerAliveInterval=60 \
          -o ServerAliveCountMax=120 \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          set -e
          cd ~/ShopPlus

          echo "📥 Pull latest code"
          git fetch origin
          git reset --hard origin/main

          # REMOVED: docker compose down (Don't kill the site yet!)
          # REMOVED: docker system prune (Don't delete cache yet, we need it for speed!)

          echo "🏗 Build images (Site is STILL ONLINE)"
          # Removed --no-cache to speed up deployment significantly
          docker compose build

          echo "🚀 Refresh containers (Minimal Downtime)"
          # This replaces old containers with new ones instantly
          docker compose up -d --remove-orphans

          echo "🗄 Run migrations"
          docker compose exec -T backend python manage.py migrate --noinput

          echo "🎨 Collect static files"
          docker compose exec -T backend python manage.py collectstatic --noinput

          echo "🧹 Cleanup old images (Safe to do now)"
          docker image prune -f

          echo "✅ Deployment finished"
          EOF


# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# concurrency:
#   group: production-deploy
#   cancel-in-progress: true

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

#       - name: Deploy to EC2
#         run: |
#           ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

#           set -e
#           cd ~/ShopPlus

#           echo "📥 Pull latest code"
#           git fetch origin
#           git reset --hard origin/main

#           echo "🏗 Build containers"
#           docker compose up -d --build

#           echo "🗄 Run migrations"
#           docker compose exec -T backend python manage.py migrate --noinput

#           echo "🎨 Collect static"
#           docker compose exec -T backend python manage.py collectstatic --noinput

#           echo "✅ Deployment Finished"

#           EOF